### ISSUE TITLE
Programming custom nrf52832 board

### ISSUE THREAD

**Issue by kungfupizza** [sparkfun/nRF52832_Breakout#12]
Hi, 
I was using Sparkfun nRF52832 board to test my application, programming it with FTDI over Arduino IDE. Now I made my own PCB and found out that the IC doesn't have bootloader in it and I cannot program it using Arduino IDE. 

Fortunately I have SWDIO, SWCLK, P26 and P27 pins available for me out along with a RST and P06 button.

For HW, I have ST-Link v2 and some STM32 boards with SWD. I have also bought a nrf52 DK. 

How do I start with this blank IC now? Any solution?

**Comment by santaimpersonator** [comment]
Unfortunately, this isn't actually an issue with the board and is more of a technical assistance related question. Please head of to our [forum](https://forum.sparkfun.com/) and post a topic. Please note that your issue is probably outside the scope of our support team and may not be address by them directly (i.e. they may just point you to some useful resources). However, someone in the community may be able to help.

That being said, it looks like we cover how to program the bootloader in the [hookup guide](https://learn.sparkfun.com/tutorials/nrf52832-breakout-board-hookup-guide#resources--going-further). Also, it looks like someone has already addressed flashing the bootloader in issue #6.
